### PR TITLE
Stereo VST plugin

### PR DESCRIPTION
**Pull request by theglobe**
Hi,

Thank you for this nice piece of software! I saw that you updated with a stereo plugin for ladspa and I recently made a stereo version of the VST plugin, which I've used in Davinci Resolve (video editing) in Windows. 

It works by duplicating the original plugin for the two channels (same solution as yours), and works with mono channels as well (although a bit inefficiently since the extra channel is still there).

Something that bugs me in stereo mode is that the channels work completely independently and it sounds like it's shifting back and forth between L-R . A better solution would be that the plug-in uses both channels combined for triggering and then process the two channels independently.

Another thing nice to have would be a dry/wet mix control. 

Kind regards,
Jaroslav

### CODE REVIEW

**Comment by werman** [comment]
Hi,
Thanks for looking into this!

> Something that bugs me in stereo mode is that the channels work completely independently and it sounds like it's shifting back and forth between L-R

Interesting, I didn't hear anything wrong when tested with my mic which seems to have 2 channels but I'm not sure.

> and works with mono channels as well (although a bit inefficiently since the extra channel is still there).

Doesn't VST support several sub-plugins in one (like in ladspa)? I'm not sure, could you look at it? It would be better to have one for mono and one for stereo.

> Another thing nice to have would be a dry/wet mix control.

I don't have knowledge in audio processing so looked this up and I'm not sure what is the point of it, could you explain it please?

Also your pull request cannot be rebased.

**Comment by theglobe** [comment]
> > Something that bugs me in stereo mode is that the channels work completely independently and it sounds like it's shifting back and forth between L-R
> 
> Interesting, I didn't hear anything wrong when tested with my mic which seems to have 2 channels but I'm not sure.

It is noticeable on noisy stereo recordings where the plugin on one channel might trigger and open for some voice while the other channel does not.
 
> > and works with mono channels as well (although a bit inefficiently since the extra channel is still there).
> 
> Doesn't VST support several sub-plugins in one (like in ladspa)? I'm not sure, could you look at it? It would be better to have one for mono and one for stereo.

It seems that most VST plugins are released in separate versions for mono and stereo.

> 
> > Another thing nice to have would be a dry/wet mix control.
> 
> I don't have knowledge in audio processing so looked this up and I'm not sure what is the point of it, could you explain it please?

This is basically a way to let some of the original signal through and lessen the effect of the plugin. 100% wet means that all of the output signal has been processed (like the plugin works now) while 0% wet (and thus 100% dry) means that all of the signal has been by-passed.

This is useful sometimes, when the effect of the plugin is too noticeable and the output goes abruptly to quiet in between voices, and it would sound better to let some of the original noise through. Right now I can get this effect by duplicating a track and inserting the plugin on one of the tracks, then mix the two tracks together (this uses up one extra audio track).

Another benefit in having this as a parameter is that it would be possible to automate it in the audio software (i.e. to vary the parameter along the track)

> 
> Also your pull request cannot be rebased.
I'm not an expert in git, but to me it seems that the branches are in sync
```
$ git merge upstream/master
Already up to date.
```
Can you see what is causing the conflict? Maybe I should just re-do the fork?

**Comment by werman** [comment]
> It seems that most VST plugins are released in separate versions for mono and stereo.

In SDK interface there is a notion of "program" but I'm not sure if that's it. Then better to compile two libraries: mono and stereo versions. 

> This is useful sometimes, when the effect of the plugin is too noticeable and the output goes abruptly to quiet in between voices, and it would sound better to let some of the original noise through. Right now I can get this effect by duplicating a track and inserting the plugin on one of the tracks, then mix the two tracks together (this uses up one extra audio track).

Makes sense

> Can you see what is causing the conflict? Maybe I should just re-do the fork?

Ugh, it's just me not understanding github interface, it fails rebasing but merge is fine.

**Comment by gnif** [comment]
I am not sure why this would be a valid or useful addition. Voice is a mono source, unless you're doing something fancy like using multiple microphones on a stage, in which case you would not be wanting this filter at all. Just pick off one channel, just because there are two doesn't mean you must use both.

> Another thing nice to have would be a dry/wet mix control.

It is not up to the plugin to implement this, the host application does this. For example, Carla has a Dry/Wet control for every single plugin.

> I don't have knowledge in audio processing so looked this up and I'm not sure what is the point of it, could you explain it please?

Dry/Wet is just how much of the original source should be mixed into the output. A completely dry signal has had zero processing applied, conversely fully wet is only the processed signal is at the output. It can be useful to mix the signal when the filtering is a bit too aggressive, or you want to retain some of the background noise (say an audience clapping) but at a reduced level.

**Comment by werman** [comment]
> I am not sure why this would be a valid or useful addition. Voice is a mono source, unless you're doing something fancy like using multiple microphones on a stage, in which case you would not be wanting this filter at all. Just pick off one channel, just because there are two doesn't mean you must use both.
> 
Some mics do seem to be stereo. But yes, I agree, stereo version of the plugin is not that useful.
 
> > Another thing nice to have would be a dry/wet mix control.
> 
> It is not up to the plugin to implement this, the host application does this. For example, Carla has a Dry/Wet control for every single plugin.
> 
Good point. I also have a feedback that it may be good to generate some noise because people find complete silence in voip apps as an indication that something going wrong with mic/connection.

> > I don't have knowledge in audio processing so looked this up and I'm not sure what is the point of it, could you explain it please?
> 
> Dry/Wet is just how much of the original source should be mixed into the output. A completely dry signal has had zero processing applied, conversely fully wet is only the processed signal is at the output. It can be useful to mix the signal when the filtering is a bit too aggressive, or you want to retain some of the background noise (say an audience clapping) but at a reduced level.

**Comment by theglobe** [comment]
> I am not sure why this would be a valid or useful addition. Voice is a
> mono source, unless you're doing something fancy like using multiple
> microphones on a stage, in which case you would not be wanting this filter
> at all. Just pick off one channel, just because there are two doesn't mean
> you must use both.
>
> Some mics do seem to be stereo. But yes, I agree, stereo version of the
> plugin is not that useful.
>
I do videography and all cameras and phones produce a stereo track. If the
channels are processed independently it will be heard when one channel
opens for voice and the other doesn't or even if they don't open
simultaneously. The plugin should control both channels simultaneously
based on the loudest(?) input of the two channels. Thus it should be a true
two channel (at the processing stage) version of the plugin. I'm working on
this but quite slowly.

> Another thing nice to have would be a dry/wet mix control.
>
> It is not up to the plugin to implement this, the host application does
> this. For example, Carla has a Dry/Wet control for every single plugin.
>
> Good point. I also have a feedback that it may be good to generate some
> noise because people find complete silence in voip apps as an indication
> that something going wrong with mic/connection.
>
> I don't have knowledge in audio processing so looked this up and I'm not
> sure what is the point of it, could you explain it please?
>
> Dry/Wet is just how much of the original source should be mixed into the
> output. A completely dry signal has had zero processing applied, conversely
> fully wet is only the processed signal is at the output. It can be useful
> to mix the signal when the filtering is a bit too aggressive, or you want
> to retain some of the background noise (say an audience clapping) but at a
> reduced level.
>
> This is quite easy to achieve after processing and some hosts have this
option for all plugins, but not the programs I'm using.

I must say that I might have a very special use case and the plugin is as
it is now perfectly useful for most applications.

Kind regards,
Jaroslav

**Comment by werman** [comment]
> I do videography and all cameras and phones produce a stereo track. If the channels are processed independently it will be heard when one channel opens for voice and the other doesn't or even if they don't open simultaneously. The plugin should control both channels simultaneously based on the loudest(?) input of the two channels. Thus it should be a true two channel (at the processing stage) version of the plugin. I'm working on this but quite slowly.

Interesting, so you want to activate processing for both channels even if one passes the threshold https://github.com/werman/noise-suppression-for-voice/blob/29891723f9961629e39fafa0f3fd8dbf846d08a4/src/rnnoise/src/denoise.c#L487-L490

> option for all plugins, but not the programs I'm using.

I agree, not every program has such options e.g. I'm using this plugin in pulseaudio on Linux to remove noise in voip apps and I don't have any other posteffects.

**Comment by gnif** [comment]
> I do videography and all cameras and phones produce a stereo track

It is perhaps stereo but it's still coming from a mono source, I highly recommend either picking off one channel or down-mixing to mono before filtering, this would be far more resource effective then running a stereo version of this filter.

> I agree, not every program has such options e.g. I'm using this plugin in pulseaudio on Linux to remove noise in voip apps and I don't have any other posteffects.

I suggest you run jack2 instead and configure pulseaudio to use jack as it's backend, it's a little more complicated to setup but once you get it working you can use a tool like `Carla` from KxStudio to easily create filter graphs.

Btw, thanks a ton for this plugin, it is extremely useful.

**Comment by werman** [comment]
> I suggest you run jack2 instead and configure pulseaudio to use jack as it's backend, it's a little more complicated to setup but once you get it working you can use a tool like Carla from KxStudio to easily create filter graphs.

Maybe it would be a better setup and maybe I would try it some time later but current one is relatively simple (if that word could apply to pulseaudio) and it kinda works... unless mic gets unplugged or pulseaudio decides to be mean to my plugin... The last one didn't happen for some time.

> Btw, thanks a ton for this plugin, it is extremely useful.

Thanks, I just packaged the original library =) The strange part is that I still don't see this denoise library or research used anywhere beside the [libopus](http://opus-codec.org/release/stable/2018/10/18/libopus-1_3.html) where it is used for speech/music classification. But it removes noise so much better that any built-it noise cancelling in voip and other apps.

**Comment by theglobe** [comment]
What is the status of this request? We had a discussion about using stereo channels and a dry/wet parameter.

The current change here is to use stereo by running two channels in parallel, in the same way as the LADSPA plugin does, and now I added a parameter for VAD.

**Comment by werman** [comment]
The way forward would be to compile two plugins, one for mono and one for stereo. I'll think about it.

Regarding addition of VAD parameter to VST, could you make a separate PR? 
And I could give feedback on it while I'm here:
- Name variables like in other places, e.g.:
```
static const char* paramVadThresholdLabel = "Voice Activity Detection Threshold";
```
- Don't use `#define`, use `static const`

**Comment by gnif** [comment]
This plugin can not work as a stereo plugin unless the rnnoise library is updated to support it. I have experimented with this and found that when using it on stereo sources one channel may detect voice while the other doesn't, even though the voice is present in both channels. The result is very hard to listen to. rnnoise needs the ability to inform the other channel if there is voice present when it performs processing so that the output is not gated when it shouldn't be.

**Comment by theglobe** [comment]
> This plugin can not work as a stereo plugin unless the rnnoise library is updated to support it. I have experimented with this and found that when using it on stereo sources one channel may detect voice while the other doesn't, even though the voice is present in both channels. The result is very hard to listen to. rnnoise needs the ability to inform the other channel if there is voice present when it performs processing so that the output is not gated when it shouldn't be.

I Agree, both channels should open and close simultaneously. Any idea how this can be made?

I am thinking about creating a common input buffer consisting of a mix of the two channels and then somehow make RnNoiseCommonPlugin::process() use the common buffer for triggering.

**Pull request closed without merging**
