### PR TITLE
RnNoise v0.2

### PR DESCRIPTION
**Pull request by pengzhendong**

### CODE REVIEW

**Comment by werman** [comment]
There are additional changes beside rnnoise update, could you add why change was made to the respective commits?

**Comment by pengzhendong** [comment]
> There are additional changes beside rnnoise update, could you add why change was made to the respective commits?

They are all frome the rnnoise update except for the google style and lv2 bug.

**Comment by XCroatoanX** [comment]
@pengzhendong 
Hi, thank you very much for your PR!
Is there maybe a changelog how it will improve the noise suppresion?

**Comment by pengzhendong** [comment]
> @pengzhendong Hi, thank you very much for your PR! Is there maybe a changelog how it will improve the noise suppresion?

Sorry, I don't know. You could refer to the original repository: https://github.com/xiph/rnnoise

**Comment by DmitriyFrogo** [comment]
> how it will improve the noise suppresion?

All time using/testing this plugin, I encountered some artifacts when somebody singing/screaming, also it has issues with sounds "ss", "sh", "ch"
In new version, most of them is gone

For personal testing purposes I created one file with part of song and processed it with same settings, but one from old RNNoise 1.03 and second from RNNoise + this PR
This song not DMCA-free, so I uploaded it here for you:
https://pixeldrain.com/l/TCmpJ4xa

The difference is obvious in first 5-10 seconds

**Comment by XCroatoanX** [comment]
> The difference is obvious in first 5-10 seconds

Wow, thank you very much, the difference is indeed day and night, can’t wait to have the update on Arch!

**Comment by DmitriyFrogo** [comment]
> can’t wait to have the update on Arch!

If you can't wait, like me, maybe you can build it for yourself like I did, by forking https://github.com/pengzhendong/noise-suppression-for-voice and using Github Actions workflow

**Comment by pengzhendong** [comment]
> > can’t wait to have the update on Arch!
> 
> If you can't wait, like me, maybe you can build it for yourself like I did, by forking https://github.com/pengzhendong/noise-suppression-for-voice and using Github Actions workflow

I built the LADSPA plugin with MSVC using a GitHub Actions workflow, but it failed. However, it succeeded on my local machine.

**Comment by DmitriyFrogo** [comment]
@pengzhendong 
Strange thing, because the day before it finished without issues, but today I have same issues
I deleted that repo after compiling so we can't see logs of successful build

But we have logs from GH actions from this repo after you created this PR
https://github.com/werman/noise-suppression-for-voice/actions/runs/9017804308

Seems like, yesterday it uses different MSVC version
In this workflow it uses `19.38.33135.0`

**Comment by pengzhendong** [comment]
> om this repo after

It doesn't build all plugins:

https://github.com/werman/noise-suppression-for-voice/blob/c1cf4307c75abed8e3ecccdd23a35f7782feaf69/.github/workflows/githubci.yml#L15

**Comment by DmitriyFrogo** [comment]
@pengzhendong 
Sorry, I can't help you with that, I'm even not a programmer :D
I couldn't wait when @werman merge this PR, and just forked your repo yesterday, enabled and started release workflow, it builded three files for me: linux-rnnoise.zip, macos-rnnoise.zip, win-rnnoise.zip, I downloaded win-rnnoise.zip, and deleted repo :D
Yesterday it works, today not

**Comment by DmitriyFrogo** [comment]
I see OBS also have issues with rnnoise compilation with newer compilers and they fixed it
Maybe it's similar issue?

https://github.com/obsproject/obs-studio/pull/10665

**Comment by pengzhendong** [comment]
> I see OBS also have issues with rnnoise compilation with newer compilers and they fixed it我发现 OBS 在使用较新的编译器进行 rnnoise 编译时也存在问题，他们修复了该问题 Maybe it's similar issue? 也许是类似的问题？
> 
> [obsproject/obs-studio#10665](https://github.com/obsproject/obs-studio/pull/10665)

Not the same issue. The issue is about the LADSPA plugin, not rnnoise.

**Comment by werman** [comment]
Thanks @pengzhendong, I updated rnnoise myself since I wanted to make the update cleaner: https://github.com/werman/noise-suppression-for-voice/commits/develop/

Downgraded MSVC to 2019 to solve compiler crash. For now `BUILD_RTCD` is not used on ci since that MSVC doesn't support sse 4.2.

Could someone test the build (https://github.com/werman/noise-suppression-for-voice/actions/runs/9140756650)?

**Comment by XCroatoanX** [comment]
> Could someone test the build (https://github.com/werman/noise-suppression-for-voice/actions/runs/9140756650)?

I can try and test on arch, if needed

**Comment by pallaswept** [comment]
> Thanks @pengzhendong, I updated rnnoise myself since I wanted to make the update cleaner: https://github.com/werman/noise-suppression-for-voice/commits/develop/
> 
> Downgraded MSVC to 2019 to solve compiler crash. For now `BUILD_RTCD` is not used on ci since that MSVC doesn't support sse 4.2.
> 
> Could someone test the build (https://github.com/werman/noise-suppression-for-voice/actions/runs/9140756650)?

I don't normally use VST, so I'm not a good test for that (because I would not really know if it failed) but I did test the ladspa version on tumbleweed, and it works great!

Thanks SOOOO much for updating this repo! It's a really big deal for people using system packages, who nearly always get their sources from here rather than a fork.

Also it is nice to know that you are alive and well :D Thanks so much for all the annoying noises we didn't have to listen to because of you! <3

**Comment by pallaswept** [comment]
> For now `BUILD_RTCD` is not used on ci since that MSVC doesn't support sse 4.2.

FYI I built this as an opensuse package, with `BUILD_RTCD`, and it works fine.

**Comment by werman** [comment]
@pallaswept Thanks!

**Pull request closed without merging**
